# Generated by Django 4.2.1 on 2023-06-06 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ф.И.О')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Докторлар',
            },
        ),
        migrations.CreateModel(
            name='RoomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номи')),
                ('price', models.FloatField(default=0, verbose_name='Нархи')),
            ],
            options={
                'verbose_name': 'Хона хизмати',
                'verbose_name_plural': 'Хоналар хизмати',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=150, verbose_name='Хона тури')),
            ],
            options={
                'verbose_name': 'Хона тури',
                'verbose_name_plural': 'Хона турлари',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, verbose_name='Номи')),
                ('service_price', models.FloatField(default=0, verbose_name='Нархи')),
            ],
            options={
                'verbose_name': 'Хизмат тури',
                'verbose_name_plural': 'Хизмат турлари',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=150, verbose_name='Ракам')),
                ('room_personal', models.IntegerField(verbose_name='Сигим')),
                ('room_patients', models.IntegerField(default=0, verbose_name='Буш')),
                ('room_price', models.FloatField(verbose_name='Нархи')),
                ('room_comfortable', models.CharField(choices=[('Lux', 'Lux'), ('Oddiy', 'Oddiy')], max_length=150, verbose_name='Кулайлиги')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roomtype', verbose_name='Хона тури')),
            ],
            options={
                'verbose_name': 'Хона',
                'verbose_name_plural': 'Хоналар',
                'ordering': ('room_number',),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_name', models.CharField(blank=True, max_length=200, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Ф.И.О')),
                ('pass_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Паспорт сериа')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Тел. ракам')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Манзил')),
                ('birthday', models.DateField(null=True, verbose_name='Тугилган сана')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Руйхатдан утган сана')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Муддати')),
                ('food', models.BooleanField(default=False, verbose_name='Таом')),
                ('food_amount', models.FloatField(default=0, verbose_name='Таом нархи')),
                ('food_duration', models.IntegerField(blank=True, null=True, verbose_name='Таом Муддати')),
                ('food_refund', models.FloatField(default=0, verbose_name='Таомдан кайтарилган сумма')),
                ('massaj1', models.BooleanField(default=False, verbose_name='Массаж котталар учун')),
                ('massaj1_amount', models.FloatField(default=0, verbose_name='Массаж котталар учун нархи')),
                ('massaj1_duration', models.IntegerField(blank=True, null=True, verbose_name='Массаж котталар учун Муддати')),
                ('massaj1_refund', models.FloatField(default=0, verbose_name='Массаж котталар учун кайтарилган сумма')),
                ('massaj2', models.BooleanField(default=False, verbose_name='Массаж ёшболлар учун')),
                ('massaj2_amount', models.FloatField(default=0, verbose_name='Массаж ёшболлар учун нархи')),
                ('massaj2_duration', models.IntegerField(blank=True, null=True, verbose_name='Массаж ёшболлар учун муддати')),
                ('massaj2_refund', models.FloatField(default=0, verbose_name='Массаж ёшболлар учун кайтарилган сумма')),
                ('from_date', models.DateTimeField(blank=True, null=True, verbose_name='Хона бант килинган сана')),
                ('room_refund', models.FloatField(default=0, verbose_name='Хонадан кайтарилган сумма')),
                ('total_refund', models.FloatField(default=0, verbose_name='Кайтарилган сумма')),
                ('room_amount', models.FloatField(default=0, verbose_name='Хона жами сумма')),
                ('total_amount', models.FloatField(default=0, verbose_name='Жами сумма')),
                ('room_status', models.BooleanField(default=False, verbose_name='Хона')),
                ('doctor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.doctor', verbose_name='Доктор')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.room', verbose_name='Хона раками')),
                ('service', models.ManyToManyField(blank=True, null=True, to='api.service', verbose_name='Хизмат турлари')),
            ],
            options={
                'verbose_name': 'Бемор',
                'verbose_name_plural': 'Беморлар',
            },
        ),
    ]
