# Generated by Django 4.2.1 on 2023-05-31 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_roominfo_patient_alter_roominfo_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominfo',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patient', verbose_name='Бемор'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor', verbose_name='Доктор'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='service',
            field=models.ManyToManyField(to='api.service', verbose_name='Хизмат турлари'),
        ),
    ]
