# Generated by Django 4.2.1 on 2023-05-31 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_patientroomservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomInfo',
        ),
    ]
