# Generated by Django 4.2.1 on 2023-05-31 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_roominfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
    ]
