# Generated by Django 4.2.1 on 2023-05-31 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.doctor', verbose_name='Доктор'),
        ),
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Муддати')),
                ('room_amount', models.FloatField(default=0, verbose_name='Хона жами сумма')),
                ('room_refund', models.FloatField(default=0, verbose_name='Хонадан кайтарилган сумма')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patient', verbose_name='Бемор')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.room', verbose_name='Хона')),
            ],
            options={
                'verbose_name': 'Хона малумоти',
                'verbose_name_plural': 'Хоналар малумоти',
            },
        ),
        migrations.CreateModel(
            name='PatientRoomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_refund', models.FloatField(default=0, verbose_name='Кайтарилган сумма')),
                ('service_duration', models.IntegerField(default=0, verbose_name='Муддати')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roomservice')),
            ],
            options={
                'verbose_name': 'Бемор танлаган хизмат тури',
                'verbose_name_plural': 'Бемор танлаган хизмат турлари',
            },
        ),
    ]
