# Generated by Django 4.2.1 on 2023-05-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_patient_doctor_roominfo_patientroomservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominfo',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
