# Generated by Django 4.2.1 on 2023-06-04 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_roominfo_room_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominfo',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='roominfo',
            name='room',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='status',
            new_name='room_status',
        ),
        migrations.RemoveField(
            model_name='roomservice',
            name='service_amount',
        ),
        migrations.RemoveField(
            model_name='roomservice',
            name='service_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Муддати'),
        ),
        migrations.AddField(
            model_name='patient',
            name='food',
            field=models.BooleanField(default=False, verbose_name='Таом'),
        ),
        migrations.AddField(
            model_name='patient',
            name='food_amount',
            field=models.FloatField(default=0, verbose_name='Таом нархи'),
        ),
        migrations.AddField(
            model_name='patient',
            name='food_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Таом Муддати'),
        ),
        migrations.AddField(
            model_name='patient',
            name='food_refund',
            field=models.FloatField(default=0, verbose_name='Таомдан кайтарилган сумма'),
        ),
        migrations.AddField(
            model_name='patient',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.room', verbose_name='Хона раками'),
        ),
        migrations.AddField(
            model_name='patient',
            name='room_amount',
            field=models.FloatField(default=0, verbose_name='Хона жами сумма'),
        ),
        migrations.AddField(
            model_name='patient',
            name='room_refund',
            field=models.FloatField(default=0, verbose_name='Хонадан кайтарилган сумма'),
        ),
        migrations.AddField(
            model_name='roomservice',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Таомнома'),
        ),
        migrations.AddField(
            model_name='roomservice',
            name='price',
            field=models.FloatField(default=0, verbose_name='Таомнома нархи'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.doctor', verbose_name='Доктор'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='api.service', verbose_name='Хизмат турлари'),
        ),
        migrations.DeleteModel(
            name='PatientRoomService',
        ),
        migrations.DeleteModel(
            name='RoomInfo',
        ),
    ]
