# Generated by Django 4.2.1 on 2023-06-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_roominfo_patient_remove_roominfo_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='massaj1',
            field=models.BooleanField(default=False, verbose_name='Массаж котталар учун'),
        ),
        migrations.AddField(
            model_name='patient',
            name='massaj1_amount',
            field=models.FloatField(default=0, verbose_name='Массаж котталар учун нархи'),
        ),
        migrations.AddField(
            model_name='patient',
            name='massaj1_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Массаж котталар учун Муддати'),
        ),
        migrations.AddField(
            model_name='patient',
            name='massaj1_refund',
            field=models.FloatField(default=0, verbose_name='Массаж котталар учун кайтарилган сумма'),
        ),
        migrations.AddField(
            model_name='patient',
            name='massaj2',
            field=models.BooleanField(default=False, verbose_name='Массаж ёшболлар учун'),
        ),
        migrations.AddField(
            model_name='patient',
            name='massaj2_amount',
            field=models.FloatField(default=0, verbose_name='Массаж ёшболлар учун нархи'),
        ),
        migrations.AddField(
            model_name='patient',
            name='massaj2_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Массаж ёшболлар учун муддати'),
        ),
        migrations.AddField(
            model_name='patient',
            name='massaj2_refund',
            field=models.FloatField(default=0, verbose_name='Массаж ёшболлар учун кайтарилган сумма'),
        ),
    ]
